// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/todos/:id/archive': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id]/archive.post').default>>>>
    }
    '/api/todos/:id/complete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id]/complete.post').default>>>>
    }
    '/api/todos/:id/reopen': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id]/reopen.post').default>>>>
    }
    '/api/todos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}